// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `AriaMapInformation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __AriaMapInformation_h__
#define __AriaMapInformation_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace RoboCompAriaMapInformation
{

class AriaMapInformation;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompAriaMapInformation::AriaMapInformation>&);
::IceProxy::Ice::Object* upCast(::IceProxy::RoboCompAriaMapInformation::AriaMapInformation*);

}

}

namespace RoboCompAriaMapInformation
{

class AriaMapInformation;
bool operator==(const AriaMapInformation&, const AriaMapInformation&);
bool operator<(const AriaMapInformation&, const AriaMapInformation&);
::Ice::Object* upCast(::RoboCompAriaMapInformation::AriaMapInformation*);
typedef ::IceInternal::Handle< ::RoboCompAriaMapInformation::AriaMapInformation> AriaMapInformationPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompAriaMapInformation::AriaMapInformation> AriaMapInformationPrx;
void __patch(AriaMapInformationPtr&, const ::Ice::ObjectPtr&);

}

namespace RoboCompAriaMapInformation
{

struct mapPose
{
    ::Ice::Double X;
    ::Ice::Double Y;
    ::Ice::Double Th;
};

typedef ::std::vector< ::RoboCompAriaMapInformation::mapPose> mapPoseList;

typedef ::std::vector< ::std::string> stringList;

struct MapInfo
{
    ::Ice::Int numGoals;
    ::RoboCompAriaMapInformation::stringList listGoals;
    ::RoboCompAriaMapInformation::mapPoseList goalPosition;
};

struct GoalInfo
{
    ::Ice::Int currentGoal;
    ::Ice::Double goalState;
};

}

namespace Ice
{
template<>
struct StreamableTraits< ::RoboCompAriaMapInformation::mapPose>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 24;
    static const bool fixedLength = true;
};

template<class S>
struct StreamWriter< ::RoboCompAriaMapInformation::mapPose, S>
{
    static void write(S* __os, const ::RoboCompAriaMapInformation::mapPose& v)
    {
        __os->write(v.X);
        __os->write(v.Y);
        __os->write(v.Th);
    }
};

template<class S>
struct StreamReader< ::RoboCompAriaMapInformation::mapPose, S>
{
    static void read(S* __is, ::RoboCompAriaMapInformation::mapPose& v)
    {
        __is->read(v.X);
        __is->read(v.Y);
        __is->read(v.Th);
    }
};

template<>
struct StreamableTraits< ::RoboCompAriaMapInformation::MapInfo>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 6;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::RoboCompAriaMapInformation::MapInfo, S>
{
    static void write(S* __os, const ::RoboCompAriaMapInformation::MapInfo& v)
    {
        __os->write(v.numGoals);
        __os->write(v.listGoals);
        __os->write(v.goalPosition);
    }
};

template<class S>
struct StreamReader< ::RoboCompAriaMapInformation::MapInfo, S>
{
    static void read(S* __is, ::RoboCompAriaMapInformation::MapInfo& v)
    {
        __is->read(v.numGoals);
        __is->read(v.listGoals);
        __is->read(v.goalPosition);
    }
};

template<>
struct StreamableTraits< ::RoboCompAriaMapInformation::GoalInfo>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 12;
    static const bool fixedLength = true;
};

template<class S>
struct StreamWriter< ::RoboCompAriaMapInformation::GoalInfo, S>
{
    static void write(S* __os, const ::RoboCompAriaMapInformation::GoalInfo& v)
    {
        __os->write(v.currentGoal);
        __os->write(v.goalState);
    }
};

template<class S>
struct StreamReader< ::RoboCompAriaMapInformation::GoalInfo, S>
{
    static void read(S* __is, ::RoboCompAriaMapInformation::GoalInfo& v)
    {
        __is->read(v.currentGoal);
        __is->read(v.goalState);
    }
};

}

namespace RoboCompAriaMapInformation
{

class Callback_AriaMapInformation_mapInformation_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AriaMapInformation_mapInformation_Base> Callback_AriaMapInformation_mapInformationPtr;

class Callback_AriaMapInformation_robotInformation_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AriaMapInformation_robotInformation_Base> Callback_AriaMapInformation_robotInformationPtr;

class Callback_AriaMapInformation_goalInformation_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AriaMapInformation_goalInformation_Base> Callback_AriaMapInformation_goalInformationPtr;

}

namespace IceProxy
{

namespace RoboCompAriaMapInformation
{

class AriaMapInformation : virtual public ::IceProxy::Ice::Object
{
public:

    void mapInformation(const ::RoboCompAriaMapInformation::MapInfo& info)
    {
        mapInformation(info, 0);
    }
    void mapInformation(const ::RoboCompAriaMapInformation::MapInfo& info, const ::Ice::Context& __ctx)
    {
        mapInformation(info, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_mapInformation(const ::RoboCompAriaMapInformation::MapInfo& info, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_mapInformation(info, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_mapInformation(const ::RoboCompAriaMapInformation::MapInfo& info, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_mapInformation(info, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_mapInformation(const ::RoboCompAriaMapInformation::MapInfo& info, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_mapInformation(info, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_mapInformation(const ::RoboCompAriaMapInformation::MapInfo& info, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_mapInformation(info, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_mapInformation(const ::RoboCompAriaMapInformation::MapInfo& info)
    {
        return begin_mapInformation(info, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_mapInformation(const ::RoboCompAriaMapInformation::MapInfo& info, const ::Ice::Context& __ctx)
    {
        return begin_mapInformation(info, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_mapInformation(const ::RoboCompAriaMapInformation::MapInfo& info, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_mapInformation(info, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_mapInformation(const ::RoboCompAriaMapInformation::MapInfo& info, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_mapInformation(info, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_mapInformation(const ::RoboCompAriaMapInformation::MapInfo& info, const ::RoboCompAriaMapInformation::Callback_AriaMapInformation_mapInformationPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_mapInformation(info, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_mapInformation(const ::RoboCompAriaMapInformation::MapInfo& info, const ::Ice::Context& __ctx, const ::RoboCompAriaMapInformation::Callback_AriaMapInformation_mapInformationPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_mapInformation(info, &__ctx, __del, __cookie);
    }

    void end_mapInformation(const ::Ice::AsyncResultPtr&);
    
private:

    void mapInformation(const ::RoboCompAriaMapInformation::MapInfo&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_mapInformation(const ::RoboCompAriaMapInformation::MapInfo&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void robotInformation(const ::RoboCompAriaMapInformation::mapPose& robotPosition)
    {
        robotInformation(robotPosition, 0);
    }
    void robotInformation(const ::RoboCompAriaMapInformation::mapPose& robotPosition, const ::Ice::Context& __ctx)
    {
        robotInformation(robotPosition, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_robotInformation(const ::RoboCompAriaMapInformation::mapPose& robotPosition, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_robotInformation(robotPosition, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_robotInformation(const ::RoboCompAriaMapInformation::mapPose& robotPosition, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_robotInformation(robotPosition, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_robotInformation(const ::RoboCompAriaMapInformation::mapPose& robotPosition, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_robotInformation(robotPosition, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_robotInformation(const ::RoboCompAriaMapInformation::mapPose& robotPosition, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_robotInformation(robotPosition, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_robotInformation(const ::RoboCompAriaMapInformation::mapPose& robotPosition)
    {
        return begin_robotInformation(robotPosition, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_robotInformation(const ::RoboCompAriaMapInformation::mapPose& robotPosition, const ::Ice::Context& __ctx)
    {
        return begin_robotInformation(robotPosition, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_robotInformation(const ::RoboCompAriaMapInformation::mapPose& robotPosition, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_robotInformation(robotPosition, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_robotInformation(const ::RoboCompAriaMapInformation::mapPose& robotPosition, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_robotInformation(robotPosition, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_robotInformation(const ::RoboCompAriaMapInformation::mapPose& robotPosition, const ::RoboCompAriaMapInformation::Callback_AriaMapInformation_robotInformationPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_robotInformation(robotPosition, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_robotInformation(const ::RoboCompAriaMapInformation::mapPose& robotPosition, const ::Ice::Context& __ctx, const ::RoboCompAriaMapInformation::Callback_AriaMapInformation_robotInformationPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_robotInformation(robotPosition, &__ctx, __del, __cookie);
    }

    void end_robotInformation(const ::Ice::AsyncResultPtr&);
    
private:

    void robotInformation(const ::RoboCompAriaMapInformation::mapPose&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_robotInformation(const ::RoboCompAriaMapInformation::mapPose&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void goalInformation(const ::RoboCompAriaMapInformation::GoalInfo& goal)
    {
        goalInformation(goal, 0);
    }
    void goalInformation(const ::RoboCompAriaMapInformation::GoalInfo& goal, const ::Ice::Context& __ctx)
    {
        goalInformation(goal, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_goalInformation(const ::RoboCompAriaMapInformation::GoalInfo& goal, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_goalInformation(goal, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_goalInformation(const ::RoboCompAriaMapInformation::GoalInfo& goal, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_goalInformation(goal, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_goalInformation(const ::RoboCompAriaMapInformation::GoalInfo& goal, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_goalInformation(goal, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_goalInformation(const ::RoboCompAriaMapInformation::GoalInfo& goal, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_goalInformation(goal, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_goalInformation(const ::RoboCompAriaMapInformation::GoalInfo& goal)
    {
        return begin_goalInformation(goal, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_goalInformation(const ::RoboCompAriaMapInformation::GoalInfo& goal, const ::Ice::Context& __ctx)
    {
        return begin_goalInformation(goal, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_goalInformation(const ::RoboCompAriaMapInformation::GoalInfo& goal, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_goalInformation(goal, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_goalInformation(const ::RoboCompAriaMapInformation::GoalInfo& goal, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_goalInformation(goal, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_goalInformation(const ::RoboCompAriaMapInformation::GoalInfo& goal, const ::RoboCompAriaMapInformation::Callback_AriaMapInformation_goalInformationPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_goalInformation(goal, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_goalInformation(const ::RoboCompAriaMapInformation::GoalInfo& goal, const ::Ice::Context& __ctx, const ::RoboCompAriaMapInformation::Callback_AriaMapInformation_goalInformationPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_goalInformation(goal, &__ctx, __del, __cookie);
    }

    void end_goalInformation(const ::Ice::AsyncResultPtr&);
    
private:

    void goalInformation(const ::RoboCompAriaMapInformation::GoalInfo&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_goalInformation(const ::RoboCompAriaMapInformation::GoalInfo&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<AriaMapInformation> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<AriaMapInformation*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<AriaMapInformation> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<AriaMapInformation*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<AriaMapInformation> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<AriaMapInformation*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<AriaMapInformation> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<AriaMapInformation*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<AriaMapInformation> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<AriaMapInformation*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<AriaMapInformation> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<AriaMapInformation*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<AriaMapInformation> ice_secure(bool __secure) const
    {
        return dynamic_cast<AriaMapInformation*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<AriaMapInformation> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<AriaMapInformation*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<AriaMapInformation> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<AriaMapInformation*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<AriaMapInformation> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<AriaMapInformation*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<AriaMapInformation> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<AriaMapInformation*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<AriaMapInformation> ice_twoway() const
    {
        return dynamic_cast<AriaMapInformation*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<AriaMapInformation> ice_oneway() const
    {
        return dynamic_cast<AriaMapInformation*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<AriaMapInformation> ice_batchOneway() const
    {
        return dynamic_cast<AriaMapInformation*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<AriaMapInformation> ice_datagram() const
    {
        return dynamic_cast<AriaMapInformation*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<AriaMapInformation> ice_batchDatagram() const
    {
        return dynamic_cast<AriaMapInformation*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<AriaMapInformation> ice_compress(bool __compress) const
    {
        return dynamic_cast<AriaMapInformation*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<AriaMapInformation> ice_timeout(int __timeout) const
    {
        return dynamic_cast<AriaMapInformation*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<AriaMapInformation> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<AriaMapInformation*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<AriaMapInformation> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<AriaMapInformation*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace RoboCompAriaMapInformation
{

class AriaMapInformation : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void mapInformation(const ::RoboCompAriaMapInformation::MapInfo&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void robotInformation(const ::RoboCompAriaMapInformation::mapPose&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void goalInformation(const ::RoboCompAriaMapInformation::GoalInfo&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace RoboCompAriaMapInformation
{

class AriaMapInformation : virtual public ::IceDelegate::RoboCompAriaMapInformation::AriaMapInformation,
                           virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void mapInformation(const ::RoboCompAriaMapInformation::MapInfo&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void robotInformation(const ::RoboCompAriaMapInformation::mapPose&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void goalInformation(const ::RoboCompAriaMapInformation::GoalInfo&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace RoboCompAriaMapInformation
{

class AriaMapInformation : virtual public ::IceDelegate::RoboCompAriaMapInformation::AriaMapInformation,
                           virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void mapInformation(const ::RoboCompAriaMapInformation::MapInfo&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void robotInformation(const ::RoboCompAriaMapInformation::mapPose&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void goalInformation(const ::RoboCompAriaMapInformation::GoalInfo&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace RoboCompAriaMapInformation
{

class AriaMapInformation : virtual public ::Ice::Object
{
public:

    typedef AriaMapInformationPrx ProxyType;
    typedef AriaMapInformationPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void mapInformation(const ::RoboCompAriaMapInformation::MapInfo&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___mapInformation(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void robotInformation(const ::RoboCompAriaMapInformation::mapPose&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___robotInformation(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void goalInformation(const ::RoboCompAriaMapInformation::GoalInfo&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___goalInformation(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const AriaMapInformation& l, const AriaMapInformation& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const AriaMapInformation& l, const AriaMapInformation& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace RoboCompAriaMapInformation
{

template<class T>
class CallbackNC_AriaMapInformation_mapInformation : public Callback_AriaMapInformation_mapInformation_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_AriaMapInformation_mapInformation(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_AriaMapInformation_mapInformationPtr
newCallback_AriaMapInformation_mapInformation(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AriaMapInformation_mapInformation<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_AriaMapInformation_mapInformationPtr
newCallback_AriaMapInformation_mapInformation(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AriaMapInformation_mapInformation<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_AriaMapInformation_mapInformationPtr
newCallback_AriaMapInformation_mapInformation(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AriaMapInformation_mapInformation<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_AriaMapInformation_mapInformationPtr
newCallback_AriaMapInformation_mapInformation(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AriaMapInformation_mapInformation<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_AriaMapInformation_mapInformation : public Callback_AriaMapInformation_mapInformation_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_AriaMapInformation_mapInformation(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_AriaMapInformation_mapInformationPtr
newCallback_AriaMapInformation_mapInformation(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AriaMapInformation_mapInformation<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_AriaMapInformation_mapInformationPtr
newCallback_AriaMapInformation_mapInformation(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AriaMapInformation_mapInformation<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_AriaMapInformation_mapInformationPtr
newCallback_AriaMapInformation_mapInformation(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AriaMapInformation_mapInformation<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_AriaMapInformation_mapInformationPtr
newCallback_AriaMapInformation_mapInformation(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AriaMapInformation_mapInformation<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_AriaMapInformation_robotInformation : public Callback_AriaMapInformation_robotInformation_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_AriaMapInformation_robotInformation(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_AriaMapInformation_robotInformationPtr
newCallback_AriaMapInformation_robotInformation(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AriaMapInformation_robotInformation<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_AriaMapInformation_robotInformationPtr
newCallback_AriaMapInformation_robotInformation(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AriaMapInformation_robotInformation<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_AriaMapInformation_robotInformationPtr
newCallback_AriaMapInformation_robotInformation(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AriaMapInformation_robotInformation<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_AriaMapInformation_robotInformationPtr
newCallback_AriaMapInformation_robotInformation(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AriaMapInformation_robotInformation<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_AriaMapInformation_robotInformation : public Callback_AriaMapInformation_robotInformation_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_AriaMapInformation_robotInformation(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_AriaMapInformation_robotInformationPtr
newCallback_AriaMapInformation_robotInformation(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AriaMapInformation_robotInformation<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_AriaMapInformation_robotInformationPtr
newCallback_AriaMapInformation_robotInformation(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AriaMapInformation_robotInformation<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_AriaMapInformation_robotInformationPtr
newCallback_AriaMapInformation_robotInformation(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AriaMapInformation_robotInformation<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_AriaMapInformation_robotInformationPtr
newCallback_AriaMapInformation_robotInformation(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AriaMapInformation_robotInformation<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_AriaMapInformation_goalInformation : public Callback_AriaMapInformation_goalInformation_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_AriaMapInformation_goalInformation(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_AriaMapInformation_goalInformationPtr
newCallback_AriaMapInformation_goalInformation(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AriaMapInformation_goalInformation<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_AriaMapInformation_goalInformationPtr
newCallback_AriaMapInformation_goalInformation(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AriaMapInformation_goalInformation<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_AriaMapInformation_goalInformationPtr
newCallback_AriaMapInformation_goalInformation(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AriaMapInformation_goalInformation<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_AriaMapInformation_goalInformationPtr
newCallback_AriaMapInformation_goalInformation(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AriaMapInformation_goalInformation<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_AriaMapInformation_goalInformation : public Callback_AriaMapInformation_goalInformation_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_AriaMapInformation_goalInformation(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_AriaMapInformation_goalInformationPtr
newCallback_AriaMapInformation_goalInformation(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AriaMapInformation_goalInformation<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_AriaMapInformation_goalInformationPtr
newCallback_AriaMapInformation_goalInformation(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AriaMapInformation_goalInformation<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_AriaMapInformation_goalInformationPtr
newCallback_AriaMapInformation_goalInformation(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AriaMapInformation_goalInformation<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_AriaMapInformation_goalInformationPtr
newCallback_AriaMapInformation_goalInformation(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AriaMapInformation_goalInformation<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
