// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `AriaMapInformation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include "../include/AriaMapInformation.h"
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompAriaMapInformation__AriaMapInformation__mapInformation_name = "mapInformation";

const ::std::string __RoboCompAriaMapInformation__AriaMapInformation__robotInformation_name = "robotInformation";

const ::std::string __RoboCompAriaMapInformation__AriaMapInformation__goalInformation_name = "goalInformation";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::RoboCompAriaMapInformation::upCast(::IceProxy::RoboCompAriaMapInformation::AriaMapInformation* p) { return p; }

void
::IceProxy::RoboCompAriaMapInformation::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompAriaMapInformation::AriaMapInformation>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompAriaMapInformation::AriaMapInformation;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::RoboCompAriaMapInformation::AriaMapInformation::mapInformation(const ::RoboCompAriaMapInformation::MapInfo& info, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompAriaMapInformation__AriaMapInformation__mapInformation_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompAriaMapInformation::AriaMapInformation* __del = dynamic_cast< ::IceDelegate::RoboCompAriaMapInformation::AriaMapInformation*>(__delBase.get());
            __del->mapInformation(info, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompAriaMapInformation::AriaMapInformation::begin_mapInformation(const ::RoboCompAriaMapInformation::MapInfo& info, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompAriaMapInformation__AriaMapInformation__mapInformation_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompAriaMapInformation__AriaMapInformation__mapInformation_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(info);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompAriaMapInformation::AriaMapInformation::end_mapInformation(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompAriaMapInformation__AriaMapInformation__mapInformation_name);
}

void
IceProxy::RoboCompAriaMapInformation::AriaMapInformation::robotInformation(const ::RoboCompAriaMapInformation::mapPose& robotPosition, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompAriaMapInformation__AriaMapInformation__robotInformation_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompAriaMapInformation::AriaMapInformation* __del = dynamic_cast< ::IceDelegate::RoboCompAriaMapInformation::AriaMapInformation*>(__delBase.get());
            __del->robotInformation(robotPosition, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompAriaMapInformation::AriaMapInformation::begin_robotInformation(const ::RoboCompAriaMapInformation::mapPose& robotPosition, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompAriaMapInformation__AriaMapInformation__robotInformation_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompAriaMapInformation__AriaMapInformation__robotInformation_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(robotPosition);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompAriaMapInformation::AriaMapInformation::end_robotInformation(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompAriaMapInformation__AriaMapInformation__robotInformation_name);
}

void
IceProxy::RoboCompAriaMapInformation::AriaMapInformation::goalInformation(const ::RoboCompAriaMapInformation::GoalInfo& goal, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompAriaMapInformation__AriaMapInformation__goalInformation_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompAriaMapInformation::AriaMapInformation* __del = dynamic_cast< ::IceDelegate::RoboCompAriaMapInformation::AriaMapInformation*>(__delBase.get());
            __del->goalInformation(goal, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompAriaMapInformation::AriaMapInformation::begin_goalInformation(const ::RoboCompAriaMapInformation::GoalInfo& goal, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompAriaMapInformation__AriaMapInformation__goalInformation_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompAriaMapInformation__AriaMapInformation__goalInformation_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(goal);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompAriaMapInformation::AriaMapInformation::end_goalInformation(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompAriaMapInformation__AriaMapInformation__goalInformation_name);
}

const ::std::string&
IceProxy::RoboCompAriaMapInformation::AriaMapInformation::ice_staticId()
{
    return ::RoboCompAriaMapInformation::AriaMapInformation::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::RoboCompAriaMapInformation::AriaMapInformation::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::RoboCompAriaMapInformation::AriaMapInformation);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::RoboCompAriaMapInformation::AriaMapInformation::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::RoboCompAriaMapInformation::AriaMapInformation);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompAriaMapInformation::AriaMapInformation::__newInstance() const
{
    return new AriaMapInformation;
}

void
IceDelegateM::RoboCompAriaMapInformation::AriaMapInformation::mapInformation(const ::RoboCompAriaMapInformation::MapInfo& info, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompAriaMapInformation__AriaMapInformation__mapInformation_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(info);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateM::RoboCompAriaMapInformation::AriaMapInformation::robotInformation(const ::RoboCompAriaMapInformation::mapPose& robotPosition, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompAriaMapInformation__AriaMapInformation__robotInformation_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(robotPosition);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateM::RoboCompAriaMapInformation::AriaMapInformation::goalInformation(const ::RoboCompAriaMapInformation::GoalInfo& goal, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompAriaMapInformation__AriaMapInformation__goalInformation_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(goal);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateD::RoboCompAriaMapInformation::AriaMapInformation::mapInformation(const ::RoboCompAriaMapInformation::MapInfo& info, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::RoboCompAriaMapInformation::MapInfo& __p_info, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_info(__p_info)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompAriaMapInformation::AriaMapInformation* servant = dynamic_cast< ::RoboCompAriaMapInformation::AriaMapInformation*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->mapInformation(_m_info, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::RoboCompAriaMapInformation::MapInfo& _m_info;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompAriaMapInformation__AriaMapInformation__mapInformation_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(info, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::RoboCompAriaMapInformation::AriaMapInformation::robotInformation(const ::RoboCompAriaMapInformation::mapPose& robotPosition, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::RoboCompAriaMapInformation::mapPose& __p_robotPosition, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_robotPosition(__p_robotPosition)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompAriaMapInformation::AriaMapInformation* servant = dynamic_cast< ::RoboCompAriaMapInformation::AriaMapInformation*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->robotInformation(_m_robotPosition, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::RoboCompAriaMapInformation::mapPose& _m_robotPosition;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompAriaMapInformation__AriaMapInformation__robotInformation_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(robotPosition, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::RoboCompAriaMapInformation::AriaMapInformation::goalInformation(const ::RoboCompAriaMapInformation::GoalInfo& goal, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::RoboCompAriaMapInformation::GoalInfo& __p_goal, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_goal(__p_goal)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompAriaMapInformation::AriaMapInformation* servant = dynamic_cast< ::RoboCompAriaMapInformation::AriaMapInformation*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->goalInformation(_m_goal, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::RoboCompAriaMapInformation::GoalInfo& _m_goal;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompAriaMapInformation__AriaMapInformation__goalInformation_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(goal, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Object* RoboCompAriaMapInformation::upCast(::RoboCompAriaMapInformation::AriaMapInformation* p) { return p; }

namespace
{
const ::std::string __RoboCompAriaMapInformation__AriaMapInformation_ids[2] =
{
    "::Ice::Object",
    "::RoboCompAriaMapInformation::AriaMapInformation"
};

}

bool
RoboCompAriaMapInformation::AriaMapInformation::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompAriaMapInformation__AriaMapInformation_ids, __RoboCompAriaMapInformation__AriaMapInformation_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompAriaMapInformation::AriaMapInformation::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompAriaMapInformation__AriaMapInformation_ids[0], &__RoboCompAriaMapInformation__AriaMapInformation_ids[2]);
}

const ::std::string&
RoboCompAriaMapInformation::AriaMapInformation::ice_id(const ::Ice::Current&) const
{
    return __RoboCompAriaMapInformation__AriaMapInformation_ids[1];
}

const ::std::string&
RoboCompAriaMapInformation::AriaMapInformation::ice_staticId()
{
    return __RoboCompAriaMapInformation__AriaMapInformation_ids[1];
}

::Ice::DispatchStatus
RoboCompAriaMapInformation::AriaMapInformation::___mapInformation(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RoboCompAriaMapInformation::MapInfo info;
    __is->read(info);
    __inS.endReadParams();
    mapInformation(info, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompAriaMapInformation::AriaMapInformation::___robotInformation(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RoboCompAriaMapInformation::mapPose robotPosition;
    __is->read(robotPosition);
    __inS.endReadParams();
    robotInformation(robotPosition, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompAriaMapInformation::AriaMapInformation::___goalInformation(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RoboCompAriaMapInformation::GoalInfo goal;
    __is->read(goal);
    __inS.endReadParams();
    goalInformation(goal, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompAriaMapInformation__AriaMapInformation_all[] =
{
    "goalInformation",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "mapInformation",
    "robotInformation"
};

}

::Ice::DispatchStatus
RoboCompAriaMapInformation::AriaMapInformation::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompAriaMapInformation__AriaMapInformation_all, __RoboCompAriaMapInformation__AriaMapInformation_all + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompAriaMapInformation__AriaMapInformation_all)
    {
        case 0:
        {
            return ___goalInformation(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
        case 5:
        {
            return ___mapInformation(in, current);
        }
        case 6:
        {
            return ___robotInformation(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompAriaMapInformation::AriaMapInformation::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompAriaMapInformation::AriaMapInformation::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompAriaMapInformation::__patch(AriaMapInformationPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompAriaMapInformation::AriaMapInformationPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompAriaMapInformation::AriaMapInformation::ice_staticId(), v);
    }
}
